/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OnlineStatus = IDL.Variant({
  'doNotDisturb' : IDL.Null,
  'away' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const Time = IDL.Int;
export const UserTier = IDL.Variant({
  'pro' : IDL.Null,
  'admin' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'status' : OnlineStatus,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'joinDate' : Time,
  'tier' : UserTier,
  'email' : IDL.Text,
  'profileIcon' : IDL.Text,
});
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TicketCategory = IDL.Variant({
  'other' : IDL.Null,
  'game' : IDL.Null,
  'website' : IDL.Null,
  'account' : IDL.Null,
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Nat,
  'status' : TicketStatus,
  'subject' : IDL.Text,
  'submittedAt' : Time,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'category' : TicketCategory,
});
export const GamePlayRecord = IDL.Record({
  'gameId' : GameId,
  'timestamp' : Time,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const FriendStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const FriendRequest = IDL.Record({
  'to' : IDL.Principal,
  'status' : FriendStatus,
  'from' : IDL.Principal,
  'timestamp' : Time,
});
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const GameReport = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReportStatus,
  'gameId' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'timestamp' : Time,
  'reporter' : IDL.Principal,
});
export const QuizSubmission = IDL.Record({
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'timestamp' : Time,
  'passed' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'addFavorite' : IDL.Func([GameId], [], []),
  'addQuizQuestion' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'editCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getAnyUserTier' : IDL.Func([IDL.Principal], [UserTier], ['query']),
  'getCallerFavorites' : IDL.Func([], [IDL.Vec(GameId)], ['query']),
  'getCallerRecentlyPlayed' : IDL.Func(
      [],
      [IDL.Vec(GamePlayRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getFavorites' : IDL.Func([IDL.Principal], [IDL.Vec(GameId)], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
  'getGameReports' : IDL.Func([], [IDL.Vec(GameReport)], ['query']),
  'getMySupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getPendingFriendRequests' : IDL.Func(
      [],
      [IDL.Vec(FriendRequest)],
      ['query'],
    ),
  'getQuizQuestions' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'question' : IDL.Text,
            'options' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getQuizSubmission' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(QuizSubmission)],
      ['query'],
    ),
  'getRecentlyPlayed' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GamePlayRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTier' : IDL.Func([], [UserTier], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordGamePlay' : IDL.Func([GameId], [], []),
  'removeCallerUserProfile' : IDL.Func([], [], []),
  'removeFavorite' : IDL.Func([GameId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'submitGameReport' : IDL.Func([IDL.Opt(IDL.Nat), IDL.Text], [IDL.Nat], []),
  'submitQuiz' : IDL.Func([IDL.Vec(IDL.Nat)], [QuizSubmission], []),
  'submitSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text, TicketCategory],
      [IDL.Nat],
      [],
    ),
  'updateGameReportStatus' : IDL.Func([IDL.Nat, ReportStatus], [], []),
  'updateSupportTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [], []),
  'upgradeToAdmin' : IDL.Func([], [], []),
  'upgradeToPro' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OnlineStatus = IDL.Variant({
    'doNotDisturb' : IDL.Null,
    'away' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserTier = IDL.Variant({
    'pro' : IDL.Null,
    'admin' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'status' : OnlineStatus,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'joinDate' : Time,
    'tier' : UserTier,
    'email' : IDL.Text,
    'profileIcon' : IDL.Text,
  });
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TicketCategory = IDL.Variant({
    'other' : IDL.Null,
    'game' : IDL.Null,
    'website' : IDL.Null,
    'account' : IDL.Null,
  });
  const SupportTicket = IDL.Record({
    'id' : IDL.Nat,
    'status' : TicketStatus,
    'subject' : IDL.Text,
    'submittedAt' : Time,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'category' : TicketCategory,
  });
  const GamePlayRecord = IDL.Record({ 'gameId' : GameId, 'timestamp' : Time });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const FriendStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const FriendRequest = IDL.Record({
    'to' : IDL.Principal,
    'status' : FriendStatus,
    'from' : IDL.Principal,
    'timestamp' : Time,
  });
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
  });
  const GameReport = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReportStatus,
    'gameId' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'timestamp' : Time,
    'reporter' : IDL.Principal,
  });
  const QuizSubmission = IDL.Record({
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'timestamp' : Time,
    'passed' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'addFavorite' : IDL.Func([GameId], [], []),
    'addQuizQuestion' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'editCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getAnyUserTier' : IDL.Func([IDL.Principal], [UserTier], ['query']),
    'getCallerFavorites' : IDL.Func([], [IDL.Vec(GameId)], ['query']),
    'getCallerRecentlyPlayed' : IDL.Func(
        [],
        [IDL.Vec(GamePlayRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getFavorites' : IDL.Func([IDL.Principal], [IDL.Vec(GameId)], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
    'getGameReports' : IDL.Func([], [IDL.Vec(GameReport)], ['query']),
    'getMySupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getPendingFriendRequests' : IDL.Func(
        [],
        [IDL.Vec(FriendRequest)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'question' : IDL.Text,
              'options' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getQuizSubmission' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(QuizSubmission)],
        ['query'],
      ),
    'getRecentlyPlayed' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GamePlayRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTier' : IDL.Func([], [UserTier], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordGamePlay' : IDL.Func([GameId], [], []),
    'removeCallerUserProfile' : IDL.Func([], [], []),
    'removeFavorite' : IDL.Func([GameId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'submitGameReport' : IDL.Func([IDL.Opt(IDL.Nat), IDL.Text], [IDL.Nat], []),
    'submitQuiz' : IDL.Func([IDL.Vec(IDL.Nat)], [QuizSubmission], []),
    'submitSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text, TicketCategory],
        [IDL.Nat],
        [],
      ),
    'updateGameReportStatus' : IDL.Func([IDL.Nat, ReportStatus], [], []),
    'updateSupportTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [], []),
    'upgradeToAdmin' : IDL.Func([], [], []),
    'upgradeToPro' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };