/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FriendRequest {
  'to' : Principal,
  'status' : FriendStatus,
  'from' : Principal,
  'timestamp' : Time,
}
export type FriendStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export type GameId = bigint;
export interface GamePlayRecord { 'gameId' : GameId, 'timestamp' : Time }
export interface GameReport {
  'id' : bigint,
  'status' : ReportStatus,
  'gameId' : [] | [bigint],
  'description' : string,
  'timestamp' : Time,
  'reporter' : Principal,
}
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type OnlineStatus = { 'doNotDisturb' : null } |
  { 'away' : null } |
  { 'offline' : null } |
  { 'online' : null };
export interface QuizSubmission {
  'userId' : Principal,
  'answers' : Array<bigint>,
  'score' : bigint,
  'timestamp' : Time,
  'passed' : boolean,
}
export type ReportStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null };
export interface SupportTicket {
  'id' : bigint,
  'status' : TicketStatus,
  'subject' : string,
  'submittedAt' : Time,
  'submittedBy' : Principal,
  'description' : string,
  'category' : TicketCategory,
}
export type TicketCategory = { 'other' : null } |
  { 'game' : null } |
  { 'website' : null } |
  { 'account' : null };
export type TicketStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'status' : OnlineStatus,
  'username' : string,
  'displayName' : string,
  'joinDate' : Time,
  'tier' : UserTier,
  'email' : string,
  'profileIcon' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserTier = { 'pro' : null } |
  { 'admin' : null } |
  { 'free' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'addFavorite' : ActorMethod<[GameId], undefined>,
  'addQuizQuestion' : ActorMethod<[string, Array<string>, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'declineFriendRequest' : ActorMethod<[Principal], undefined>,
  'editCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'getAllSupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getAnyUserTier' : ActorMethod<[Principal], UserTier>,
  'getCallerFavorites' : ActorMethod<[], Array<GameId>>,
  'getCallerRecentlyPlayed' : ActorMethod<[], Array<GamePlayRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getFavorites' : ActorMethod<[Principal], Array<GameId>>,
  'getFriends' : ActorMethod<[], Array<FriendRequest>>,
  'getGameReports' : ActorMethod<[], Array<GameReport>>,
  'getMySupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getPendingFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getQuizQuestions' : ActorMethod<
    [],
    Array<{ 'id' : bigint, 'question' : string, 'options' : Array<string> }>
  >,
  'getQuizSubmission' : ActorMethod<[Principal], [] | [QuizSubmission]>,
  'getRecentlyPlayed' : ActorMethod<[Principal], Array<GamePlayRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTier' : ActorMethod<[], UserTier>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordGamePlay' : ActorMethod<[GameId], undefined>,
  'removeCallerUserProfile' : ActorMethod<[], undefined>,
  'removeFavorite' : ActorMethod<[GameId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[string], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'submitGameReport' : ActorMethod<[[] | [bigint], string], bigint>,
  'submitQuiz' : ActorMethod<[Array<bigint>], QuizSubmission>,
  'submitSupportTicket' : ActorMethod<[string, string, TicketCategory], bigint>,
  'updateGameReportStatus' : ActorMethod<[bigint, ReportStatus], undefined>,
  'updateSupportTicketStatus' : ActorMethod<[bigint, TicketStatus], undefined>,
  'upgradeToAdmin' : ActorMethod<[], undefined>,
  'upgradeToPro' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];