/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    status: OnlineStatus;
    username: string;
    displayName: string;
    joinDate: Time;
    tier: UserTier;
    email: string;
    profileIcon: string;
}
export type Time = bigint;
export interface QuizSubmission {
    userId: Principal;
    answers: Array<bigint>;
    score: bigint;
    timestamp: Time;
    passed: boolean;
}
export interface GamePlayRecord {
    gameId: GameId;
    timestamp: Time;
}
export interface FriendRequest {
    to: Principal;
    status: FriendStatus;
    from: Principal;
    timestamp: Time;
}
export interface GameReport {
    id: bigint;
    status: ReportStatus;
    gameId?: bigint;
    description: string;
    timestamp: Time;
    reporter: Principal;
}
export type GameId = bigint;
export interface Message {
    content: string;
    sender: Principal;
    timestamp: Time;
    receiver: Principal;
}
export interface SupportTicket {
    id: bigint;
    status: TicketStatus;
    subject: string;
    submittedAt: Time;
    submittedBy: Principal;
    description: string;
    category: TicketCategory;
}
export enum FriendStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export enum OnlineStatus {
    doNotDisturb = "doNotDisturb",
    away = "away",
    offline = "offline",
    online = "online"
}
export enum ReportStatus {
    resolved = "resolved",
    closed = "closed",
    open = "open"
}
export enum TicketCategory {
    other = "other",
    game = "game",
    website = "website",
    account = "account"
}
export enum TicketStatus {
    resolved = "resolved",
    closed = "closed",
    open = "open",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserTier {
    pro = "pro",
    admin = "admin",
    free = "free"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptFriendRequest(from: Principal): Promise<void>;
    addFavorite(gameId: GameId): Promise<void>;
    addQuizQuestion(question: string, options: Array<string>, correctAnswerIndex: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    declineFriendRequest(from: Principal): Promise<void>;
    editCallerUserProfile(profile: UserProfile): Promise<void>;
    getAllSupportTickets(): Promise<Array<SupportTicket>>;
    getAnyUserTier(user: Principal): Promise<UserTier>;
    getCallerFavorites(): Promise<Array<GameId>>;
    getCallerRecentlyPlayed(): Promise<Array<GamePlayRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(otherUser: Principal): Promise<Array<Message>>;
    getFavorites(user: Principal): Promise<Array<GameId>>;
    getFriends(): Promise<Array<FriendRequest>>;
    getGameReports(): Promise<Array<GameReport>>;
    getMySupportTickets(): Promise<Array<SupportTicket>>;
    getPendingFriendRequests(): Promise<Array<FriendRequest>>;
    getQuizQuestions(): Promise<Array<{
        id: bigint;
        question: string;
        options: Array<string>;
    }>>;
    getQuizSubmission(user: Principal): Promise<QuizSubmission | null>;
    getRecentlyPlayed(user: Principal): Promise<Array<GamePlayRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTier(): Promise<UserTier>;
    isCallerAdmin(): Promise<boolean>;
    recordGamePlay(gameId: GameId): Promise<void>;
    removeCallerUserProfile(): Promise<void>;
    removeFavorite(gameId: GameId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendFriendRequest(toUsername: string): Promise<void>;
    sendMessage(to: Principal, content: string): Promise<void>;
    submitGameReport(gameId: bigint | null, description: string): Promise<bigint>;
    submitQuiz(answers: Array<bigint>): Promise<QuizSubmission>;
    submitSupportTicket(subject: string, description: string, category: TicketCategory): Promise<bigint>;
    updateGameReportStatus(reportId: bigint, status: ReportStatus): Promise<void>;
    updateSupportTicketStatus(ticketId: bigint, status: TicketStatus): Promise<void>;
    upgradeToAdmin(): Promise<void>;
    upgradeToPro(): Promise<void>;
}
import type { FriendRequest as _FriendRequest, FriendStatus as _FriendStatus, GameReport as _GameReport, OnlineStatus as _OnlineStatus, QuizSubmission as _QuizSubmission, ReportStatus as _ReportStatus, SupportTicket as _SupportTicket, TicketCategory as _TicketCategory, TicketStatus as _TicketStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserTier as _UserTier } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async addFavorite(arg0: GameId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async addQuizQuestion(arg0: string, arg1: Array<string>, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuizQuestion(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuizQuestion(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async declineFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineFriendRequest(arg0);
            return result;
        }
    }
    async editCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCallerUserProfile(to_candid_UserProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCallerUserProfile(to_candid_UserProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllSupportTickets(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupportTickets();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupportTickets();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnyUserTier(arg0: Principal): Promise<UserTier> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnyUserTier(arg0);
                return from_candid_UserTier_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnyUserTier(arg0);
            return from_candid_UserTier_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerFavorites(): Promise<Array<GameId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerFavorites();
            return result;
        }
    }
    async getCallerRecentlyPlayed(): Promise<Array<GamePlayRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRecentlyPlayed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRecentlyPlayed();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getFavorites(arg0: Principal): Promise<Array<GameId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites(arg0);
            return result;
        }
    }
    async getFriends(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameReports(): Promise<Array<GameReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameReports();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameReports();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySupportTickets(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySupportTickets();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySupportTickets();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingFriendRequests(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFriendRequests();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFriendRequests();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestions(): Promise<Array<{
        id: bigint;
        question: string;
        options: Array<string>;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions();
            return result;
        }
    }
    async getQuizSubmission(arg0: Principal): Promise<QuizSubmission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizSubmission(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizSubmission(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentlyPlayed(arg0: Principal): Promise<Array<GamePlayRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentlyPlayed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentlyPlayed(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTier(): Promise<UserTier> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTier();
                return from_candid_UserTier_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTier();
            return from_candid_UserTier_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordGamePlay(arg0: GameId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGamePlay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGamePlay(arg0);
            return result;
        }
    }
    async removeCallerUserProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCallerUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCallerUserProfile();
            return result;
        }
    }
    async removeFavorite(arg0: GameId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendFriendRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async submitGameReport(arg0: bigint | null, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGameReport(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGameReport(to_candid_opt_n37(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async submitQuiz(arg0: Array<bigint>): Promise<QuizSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuiz(arg0);
            return result;
        }
    }
    async submitSupportTicket(arg0: string, arg1: string, arg2: TicketCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportTicket(arg0, arg1, to_candid_TicketCategory_n38(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportTicket(arg0, arg1, to_candid_TicketCategory_n38(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateGameReportStatus(arg0: bigint, arg1: ReportStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGameReportStatus(arg0, to_candid_ReportStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGameReportStatus(arg0, to_candid_ReportStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSupportTicketStatus(arg0: bigint, arg1: TicketStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupportTicketStatus(arg0, to_candid_TicketStatus_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupportTicketStatus(arg0, to_candid_TicketStatus_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upgradeToAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToAdmin();
            return result;
        }
    }
    async upgradeToPro(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToPro();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToPro();
            return result;
        }
    }
}
function from_candid_FriendRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequest): FriendRequest {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_FriendStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendStatus): FriendStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_GameReport_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameReport): GameReport {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_OnlineStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnlineStatus): OnlineStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_SupportTicket_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportTicket): SupportTicket {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TicketCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketCategory): TicketCategory {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserTier_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserTier): UserTier {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizSubmission]): QuizSubmission | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TicketStatus;
    subject: string;
    submittedAt: _Time;
    submittedBy: Principal;
    description: string;
    category: _TicketCategory;
}): {
    id: bigint;
    status: TicketStatus;
    subject: string;
    submittedAt: Time;
    submittedBy: Principal;
    description: string;
    category: TicketCategory;
} {
    return {
        id: value.id,
        status: from_candid_TicketStatus_n12(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        description: value.description,
        category: from_candid_TicketCategory_n14(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _OnlineStatus;
    username: string;
    displayName: string;
    joinDate: _Time;
    tier: _UserTier;
    email: string;
    profileIcon: string;
}): {
    status: OnlineStatus;
    username: string;
    displayName: string;
    joinDate: Time;
    tier: UserTier;
    email: string;
    profileIcon: string;
} {
    return {
        status: from_candid_OnlineStatus_n21(_uploadFile, _downloadFile, value.status),
        username: value.username,
        displayName: value.displayName,
        joinDate: value.joinDate,
        tier: from_candid_UserTier_n16(_uploadFile, _downloadFile, value.tier),
        email: value.email,
        profileIcon: value.profileIcon
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: Principal;
    status: _FriendStatus;
    from: Principal;
    timestamp: _Time;
}): {
    to: Principal;
    status: FriendStatus;
    from: Principal;
    timestamp: Time;
} {
    return {
        to: value.to,
        status: from_candid_FriendStatus_n28(_uploadFile, _downloadFile, value.status),
        from: value.from,
        timestamp: value.timestamp
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReportStatus;
    gameId: [] | [bigint];
    description: string;
    timestamp: _Time;
    reporter: Principal;
}): {
    id: bigint;
    status: ReportStatus;
    gameId?: bigint;
    description: string;
    timestamp: Time;
    reporter: Principal;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n33(_uploadFile, _downloadFile, value.status),
        gameId: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.gameId)),
        description: value.description,
        timestamp: value.timestamp,
        reporter: value.reporter
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
}): TicketStatus {
    return "resolved" in value ? TicketStatus.resolved : "closed" in value ? TicketStatus.closed : "open" in value ? TicketStatus.open : "inProgress" in value ? TicketStatus.inProgress : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    game: null;
} | {
    website: null;
} | {
    account: null;
}): TicketCategory {
    return "other" in value ? TicketCategory.other : "game" in value ? TicketCategory.game : "website" in value ? TicketCategory.website : "account" in value ? TicketCategory.account : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    admin: null;
} | {
    free: null;
}): UserTier {
    return "pro" in value ? UserTier.pro : "admin" in value ? UserTier.admin : "free" in value ? UserTier.free : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doNotDisturb: null;
} | {
    away: null;
} | {
    offline: null;
} | {
    online: null;
}): OnlineStatus {
    return "doNotDisturb" in value ? OnlineStatus.doNotDisturb : "away" in value ? OnlineStatus.away : "offline" in value ? OnlineStatus.offline : "online" in value ? OnlineStatus.online : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): FriendStatus {
    return "pending" in value ? FriendStatus.pending : "accepted" in value ? FriendStatus.accepted : "declined" in value ? FriendStatus.declined : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
}): ReportStatus {
    return "resolved" in value ? ReportStatus.resolved : "closed" in value ? ReportStatus.closed : "open" in value ? ReportStatus.open : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendRequest>): Array<FriendRequest> {
    return value.map((x)=>from_candid_FriendRequest_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameReport>): Array<GameReport> {
    return value.map((x)=>from_candid_GameReport_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupportTicket>): Array<SupportTicket> {
    return value.map((x)=>from_candid_SupportTicket_n10(_uploadFile, _downloadFile, x));
}
function to_candid_OnlineStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnlineStatus): _OnlineStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_TicketCategory_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketCategory): _TicketCategory {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_TicketStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): _TicketStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserTier_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): _UserTier {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: OnlineStatus;
    username: string;
    displayName: string;
    joinDate: Time;
    tier: UserTier;
    email: string;
    profileIcon: string;
}): {
    status: _OnlineStatus;
    username: string;
    displayName: string;
    joinDate: _Time;
    tier: _UserTier;
    email: string;
    profileIcon: string;
} {
    return {
        status: to_candid_OnlineStatus_n5(_uploadFile, _downloadFile, value.status),
        username: value.username,
        displayName: value.displayName,
        joinDate: value.joinDate,
        tier: to_candid_UserTier_n7(_uploadFile, _downloadFile, value.tier),
        email: value.email,
        profileIcon: value.profileIcon
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketCategory): {
    other: null;
} | {
    game: null;
} | {
    website: null;
} | {
    account: null;
} {
    return value == TicketCategory.other ? {
        other: null
    } : value == TicketCategory.game ? {
        game: null
    } : value == TicketCategory.website ? {
        website: null
    } : value == TicketCategory.account ? {
        account: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} {
    return value == ReportStatus.resolved ? {
        resolved: null
    } : value == ReportStatus.closed ? {
        closed: null
    } : value == ReportStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == TicketStatus.resolved ? {
        resolved: null
    } : value == TicketStatus.closed ? {
        closed: null
    } : value == TicketStatus.open ? {
        open: null
    } : value == TicketStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnlineStatus): {
    doNotDisturb: null;
} | {
    away: null;
} | {
    offline: null;
} | {
    online: null;
} {
    return value == OnlineStatus.doNotDisturb ? {
        doNotDisturb: null
    } : value == OnlineStatus.away ? {
        away: null
    } : value == OnlineStatus.offline ? {
        offline: null
    } : value == OnlineStatus.online ? {
        online: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): {
    pro: null;
} | {
    admin: null;
} | {
    free: null;
} {
    return value == UserTier.pro ? {
        pro: null
    } : value == UserTier.admin ? {
        admin: null
    } : value == UserTier.free ? {
        free: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
